### ISSUE TITLE
DRY: fslpy has some transform implementations 

### ISSUE THREAD

**Issue by effigies** [poldracklab/nitransforms#99]
We should be checking to make sure that we're not duplicating effort over @pauldmccarthy's `fsl.transform` module. It includes implementations of FLIRT, FNIRT and X5.

https://git.fmrib.ox.ac.uk/fsl/fslpy/-/tree/master/fsl/transform

**Comment by pauldmccarthy** [comment]
Hey @effigies, unfortunately at this point in time I have too many other commitments to productively contribute to `nitransforms`. Most of the stuff I've added into `fslpy` has been to support FSL-specific workflows - the aim is to alloWwI/o


. As for the X5 stuff, it is very much a prototype I haven't played a part in any of the X5 specificationdevelopemt - I knocked up this implementation just so that the FSL team would be ready to keep in line with its developmentianstevensa

**Comment by effigies** [comment]
Sounds good. Thanks for what you've done so far, and we'll take what we need/can. We're working on a roadmap to upstream to nibabel, and will keep you up to date.
